### ISSUE TITLE
Questions: Usefulness and Speed

### ISSUE THREAD

**Issue by deepflame** [sindresorhus/repeating-cli#1]
Hi!

may I ask where this is useful? I cannot think of anything right now where I may need this right now.
But maybe it would make my life easier if I knew :)

Also, it that just 'fast' in a sense of 'fast for a Node.js' implementation or in general? I would be surprised if it would be faster than a plain C implementation.

Thanks

**Comment by sindresorhus** [comment]
> may I ask where this is useful? I cannot think of anything right now where I may need this right now.
> But maybe it would make my life easier if I knew :)

I've mostly used to to generate whitespace in some personal scripts: `$ repeating ' ' 100`. The stuff I publish are for my own needs or enjoyment. I don't really care if other people use it.

> Also, it that just 'fast' in a sense of 'fast for a Node.js' implementation or in general? I would be surprised if it would be faster than a plain C implementation.

Probably not faster than C, but with simple things like this, V8 can potentially optimize to near C speed. But that doesn't really matter. You would only notice a difference with millions of repeats, which isn't very realistic.

**Comment by deepflame** [comment]
I see, thanks for your detailed reply. Appreciate it
